### ISSUE TITLE
Provide codes for keys F13-F24

### ISSUE THREAD

**Issue by cool-RR** [autopilot-rs/autopy#36]
I use the F24 key for... Something. Currently Autopy has entries for keys F1-F12. I wish it also provided codes for F13-F24.

**Comment by cool-RR** [comment]
Awesome! Will you update here when it's available? (e.g. by closing the issue)

**Comment by msanders** [comment]
I've merged support for this now on master, will update this thread once released.

**Comment by msanders** [comment]
This is now released in [version 3.0.0](https://pypi.org/project/autopy/3.0.0/).

**Comment by cool-RR** [comment]
Awesome, thank you! 

I do have one problem. The way I use `autopy` is by injecting it into Wing IDE's internal Python, and then using it from my scripts. Unfortunately, Wing still uses Python 2.7 internally. I tried downloading the right autopy binary from PyPI, but I'm on Windows, and it looks like you don't have a Windows 64bit binary for Python 2.7. Any chance you could add that?

**Comment by msanders** [comment]
This is currently unsupported due to #23, although there should be a source distribution. If you want to give it a shot I would be interested in including it. I would strongly urge them to upgrade to Python 3, though, since Python 2.7 will hit EOL on [January 1, 2020](https://pythonclock.org/). pyo3 [no longer supports](https://github.com/PyO3/pyo3/issues/138) 2.7 so it likely won't be included in AutoPy for much longer.
