### ISSUE TITLE
autopy.key.type_string doesn't type quotes

### ISSUE THREAD

**Issue by c4f3a0ce** [autopilot-rs/autopy#43]
I am using Autopy 3.0.1 on Debian GNU/Linux and I experience rather weird problem. Whenever I call `autopy.key.type_string` or `autopy.key.tap` with either single (`'`) or double quote (`"`), i.e.:

```python
autopy.key.type_string('foo " " bar')
```

the embed quotes a simply omitted.

As far as I can tell these behavior is independent of the application in which I interact.

What could be the reason for that?

**Comment by msanders** [comment]
Thank you for the detailed report. I don't have time to test this at the moment, as it's pretty involved and requires spinning up a new virtual machine, but I think I may have found the culprit code. It looks like the quote characters are missing from this function mapping characters to key codes: https://github.com/autopilot-rs/autopilot-rs/blob/0886db6/src/key.rs#L172. If you want to take a look at it and open a PR after confirming it works on your machine I'll merge it in. Otherwise, will take a look at it later this week.

**Comment by msanders** [comment]
This is also assuming there is a bug in `XStringToKeysym` converting the character on its own without the special-casing, which is also odd but looks like it was necessary for these other keys.

**Comment by msanders** [comment]
This is fixed now on the latest release, 3.1.0.
