### ISSUE TITLE
Issues with Capture Screen Mac OS

### ISSUE THREAD

**Issue by Max604** [autopilot-rs/autopy#50]
Hi,

I'm having an issue with autopy's screen capture. It just takes screenshots of my desktop background and none of the applications in front.
MacOS 10.15.1
Python 2.7.16
I'm using:
        autopy.bitmap.capture_screen().save(file_name)

Thanks,
Max

**Comment by msanders** [comment]
Thanks for the report! The API for this must have changed in Catalina. I'm still on Mojave so there may be some delay in fixing this, since it will require me to spin up another VM or dual-boot my machine. The relevant bits of code are [here](https://github.com/autopilot-rs/autopilot-rs/blob/1bd43f08561755ae8420ad33f4d378f8c0602bd7/src/bitmap.rs#L449) and [here](https://github.com/servo/core-foundation-rs/blob/24daecbe77e90b0f58711ab67fb7dc8714f6e0ea/core-graphics/src/display.rs#L255) if anyone is interested in taking a look.

**Comment by msanders** [comment]
Hi, sorry for the delay. It looks like this is due to a change in privacy controls. In Catalina you must enable access to Screen Recording under System Preferences > Security & Privacy > Privacy > Terminal in order for the capture screen function to work correctly.
